source "https://rubygems.org"

ruby "3.3.11"

gem "rails", "~> 8.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rubocop-rails"
end

gem "bcrypt",  "~> 3.1"
gem "pundit", "~> 2.5"
gem "pagy",   "~> 43.5"
